'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OrbisPro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _error() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property _select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property back() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property back2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("back2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property home() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property logout() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property move() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property notification() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property options() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps2_back() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps2_back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps2_listmove() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps2_listmove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps2_move() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps2_move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps2_select() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps2_select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_boot() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_notification() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_notification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_trophy() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_trophy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_uiback() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_uiback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_uimove() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_uimove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ps5_uiselect() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ps5_uiselect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property trophy() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("trophy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.IO.UnmanagedMemoryStream ähnlich wie System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property trophy_offline() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("trophy_offline", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
